/*
 * This file is generated by jOOQ.
 */
package com.shashank.project.db.jooq.tables.records;


import com.shashank.project.db.jooq.tables.Contact;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContactRecord extends UpdatableRecordImpl<ContactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contact.id</code>.
     */
    public ContactRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>contact.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>contact.name</code>.
     */
    public ContactRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>contact.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>contact.email</code>.
     */
    public ContactRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>contact.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contact.mobile_number</code>.
     */
    public ContactRecord setMobileNumber(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>contact.mobile_number</code>.
     */
    public String getMobileNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>contact.is_active</code>.
     */
    public ContactRecord setIsActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>contact.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>contact.created_on</code>.
     */
    public ContactRecord setCreatedOn(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>contact.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>contact.updated_on</code>.
     */
    public ContactRecord setUpdatedOn(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>contact.updated_on</code>.
     */
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>contact.created_by</code>.
     */
    public ContactRecord setCreatedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>contact.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>contact.updated_by</code>.
     */
    public ContactRecord setUpdatedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>contact.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactRecord
     */
    public ContactRecord() {
        super(Contact.CONTACT);
    }

    /**
     * Create a detached, initialised ContactRecord
     */
    public ContactRecord(UUID id, String name, String email, String mobileNumber, Boolean isActive, OffsetDateTime createdOn, OffsetDateTime updatedOn, UUID createdBy, UUID updatedBy) {
        super(Contact.CONTACT);

        setId(id);
        setName(name);
        setEmail(email);
        setMobileNumber(mobileNumber);
        setIsActive(isActive);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ContactRecord
     */
    public ContactRecord(com.shashank.project.db.jooq.tables.pojos.Contact value) {
        super(Contact.CONTACT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setMobileNumber(value.getMobileNumber());
            setIsActive(value.getIsActive());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            resetChangedOnNotNull();
        }
    }
}
