/*
 * This file is generated by jOOQ.
 */
package com.shashank.project.db.jooq.tables.records;


import com.shashank.project.db.jooq.tables.User;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user.id</code>.
     */
    public UserRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>user.name</code>.
     */
    public UserRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.email</code>.
     */
    public UserRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.password</code>.
     */
    public UserRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.mobile_number</code>.
     */
    public UserRecord setMobileNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user.mobile_number</code>.
     */
    public String getMobileNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user.is_active</code>.
     */
    public UserRecord setIsActive(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>user.created_on</code>.
     */
    public UserRecord setCreatedOn(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>user.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>user.updated_on</code>.
     */
    public UserRecord setUpdatedOn(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>user.updated_on</code>.
     */
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>user.created_by</code>.
     */
    public UserRecord setCreatedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>user.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>user.updated_by</code>.
     */
    public UserRecord setUpdatedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>user.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(UUID id, String name, String email, String password, String mobileNumber, Boolean isActive, OffsetDateTime createdOn, OffsetDateTime updatedOn, UUID createdBy, UUID updatedBy) {
        super(User.USER);

        setId(id);
        setName(name);
        setEmail(email);
        setPassword(password);
        setMobileNumber(mobileNumber);
        setIsActive(isActive);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(com.shashank.project.db.jooq.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
            setMobileNumber(value.getMobileNumber());
            setIsActive(value.getIsActive());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            resetChangedOnNotNull();
        }
    }
}
