/*
 * This file is generated by jOOQ.
 */
package com.shashank.project.db.jooq.tables.daos;


import com.shashank.project.db.jooq.tables.Contact;
import com.shashank.project.db.jooq.tables.records.ContactRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ContactDao extends DAOImpl<ContactRecord, com.shashank.project.db.jooq.tables.pojos.Contact, UUID> {

    /**
     * Create a new ContactDao without any configuration
     */
    public ContactDao() {
        super(Contact.CONTACT, com.shashank.project.db.jooq.tables.pojos.Contact.class);
    }

    /**
     * Create a new ContactDao with an attached configuration
     */
    @Autowired
    public ContactDao(Configuration configuration) {
        super(Contact.CONTACT, com.shashank.project.db.jooq.tables.pojos.Contact.class, configuration);
    }

    @Override
    public UUID getId(com.shashank.project.db.jooq.tables.pojos.Contact object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Contact.CONTACT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchById(UUID... values) {
        return fetch(Contact.CONTACT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.shashank.project.db.jooq.tables.pojos.Contact fetchOneById(UUID value) {
        return fetchOne(Contact.CONTACT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.shashank.project.db.jooq.tables.pojos.Contact> fetchOptionalById(UUID value) {
        return fetchOptional(Contact.CONTACT.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contact.CONTACT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByName(String... values) {
        return fetch(Contact.CONTACT.NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contact.CONTACT.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByEmail(String... values) {
        return fetch(Contact.CONTACT.EMAIL, values);
    }

    /**
     * Fetch records that have <code>mobile_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfMobileNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contact.CONTACT.MOBILE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mobile_number IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByMobileNumber(String... values) {
        return fetch(Contact.CONTACT.MOBILE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfIsActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Contact.CONTACT.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByIsActive(Boolean... values) {
        return fetch(Contact.CONTACT.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfCreatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Contact.CONTACT.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByCreatedOn(OffsetDateTime... values) {
        return fetch(Contact.CONTACT.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfUpdatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Contact.CONTACT.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByUpdatedOn(OffsetDateTime... values) {
        return fetch(Contact.CONTACT.UPDATED_ON, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Contact.CONTACT.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByCreatedBy(UUID... values) {
        return fetch(Contact.CONTACT.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>updated_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchRangeOfUpdatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Contact.CONTACT.UPDATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_by IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Contact> fetchByUpdatedBy(UUID... values) {
        return fetch(Contact.CONTACT.UPDATED_BY, values);
    }
}
