/*
 * This file is generated by jOOQ.
 */
package com.shashank.project.db.jooq.tables.daos;


import com.shashank.project.db.jooq.tables.Table;
import com.shashank.project.db.jooq.tables.records.TableRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class TableDao extends DAOImpl<TableRecord, com.shashank.project.db.jooq.tables.pojos.Table, UUID> {

    /**
     * Create a new TableDao without any configuration
     */
    public TableDao() {
        super(Table.TABLE, com.shashank.project.db.jooq.tables.pojos.Table.class);
    }

    /**
     * Create a new TableDao with an attached configuration
     */
    @Autowired
    public TableDao(Configuration configuration) {
        super(Table.TABLE, com.shashank.project.db.jooq.tables.pojos.Table.class, configuration);
    }

    @Override
    public UUID getId(com.shashank.project.db.jooq.tables.pojos.Table object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Table.TABLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchById(UUID... values) {
        return fetch(Table.TABLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.shashank.project.db.jooq.tables.pojos.Table fetchOneById(UUID value) {
        return fetchOne(Table.TABLE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.shashank.project.db.jooq.tables.pojos.Table> fetchOptionalById(UUID value) {
        return fetchOptional(Table.TABLE.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Table.TABLE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByName(String... values) {
        return fetch(Table.TABLE.NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Table.TABLE.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByEmail(String... values) {
        return fetch(Table.TABLE.EMAIL, values);
    }

    /**
     * Fetch records that have <code>mobile_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfMobileNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Table.TABLE.MOBILE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mobile_number IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByMobileNumber(String... values) {
        return fetch(Table.TABLE.MOBILE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfIsActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Table.TABLE.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByIsActive(Boolean... values) {
        return fetch(Table.TABLE.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfCreatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Table.TABLE.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByCreatedOn(OffsetDateTime... values) {
        return fetch(Table.TABLE.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfUpdatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Table.TABLE.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByUpdatedOn(OffsetDateTime... values) {
        return fetch(Table.TABLE.UPDATED_ON, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Table.TABLE.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByCreatedBy(UUID... values) {
        return fetch(Table.TABLE.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>updated_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchRangeOfUpdatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Table.TABLE.UPDATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_by IN (values)</code>
     */
    public List<com.shashank.project.db.jooq.tables.pojos.Table> fetchByUpdatedBy(UUID... values) {
        return fetch(Table.TABLE.UPDATED_BY, values);
    }
}
