/*
 * This file is generated by jOOQ.
 */
package com.shashank.project.db.jooq;


import com.shashank.project.db.jooq.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_USER_CREATED_ON = Internal.createIndex(DSL.name("idx_user_created_on"), User.USER, new OrderField[] { User.USER.CREATED_ON }, false);
    public static final Index IDX_USER_EMAIL = Internal.createIndex(DSL.name("idx_user_email"), User.USER, new OrderField[] { User.USER.EMAIL }, false);
    public static final Index IDX_USER_IS_ACTIVE = Internal.createIndex(DSL.name("idx_user_is_active"), User.USER, new OrderField[] { User.USER.IS_ACTIVE }, false);
}
