/*
 * This file is generated by jOOQ.
 */
package com.shashank.project.db.jooq;


import com.shashank.project.db.jooq.tables.Contact;
import com.shashank.project.db.jooq.tables.Table;
import com.shashank.project.db.jooq.tables.User;
import com.shashank.project.db.jooq.tables.records.ContactRecord;
import com.shashank.project.db.jooq.tables.records.TableRecord;
import com.shashank.project.db.jooq.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ContactRecord> CONTACT_PKEY = Internal.createUniqueKey(Contact.CONTACT, DSL.name("contact_pkey"), new TableField[] { Contact.CONTACT.ID }, true);
    public static final UniqueKey<TableRecord> TABLE_PKEY = Internal.createUniqueKey(Table.TABLE, DSL.name("table_pkey"), new TableField[] { Table.TABLE.ID }, true);
    public static final UniqueKey<UserRecord> USER_EMAIL_UNIQUE = Internal.createUniqueKey(User.USER, DSL.name("user_email_unique"), new TableField[] { User.USER.EMAIL }, true);
    public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, DSL.name("user_pkey"), new TableField[] { User.USER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserRecord, UserRecord> USER__FK_USER_CREATED_BY = Internal.createForeignKey(User.USER, DSL.name("fk_user_created_by"), new TableField[] { User.USER.CREATED_BY }, Keys.USER_PKEY, new TableField[] { User.USER.ID }, true);
    public static final ForeignKey<UserRecord, UserRecord> USER__FK_USER_UPDATED_BY = Internal.createForeignKey(User.USER, DSL.name("fk_user_updated_by"), new TableField[] { User.USER.UPDATED_BY }, Keys.USER_PKEY, new TableField[] { User.USER.ID }, true);
}
